export const AUTH_ERROR_CODES = {
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  EMAIL_ALREADY_VERIFIED: "EMAIL_ALREADY_VERIFIED",
  TOKEN_NOT_FOUND: "TOKEN_NOT_FOUND",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  GOOGLE_ACCOUNT_EXISTS: "GOOGLE_ACCOUNT_EXISTS",
  PASSWORD_RESET_TOKEN_NOT_FOUND: "PASSWORD_RESET_TOKEN_NOT_FOUND",
  PASSWORD_RESET_TOKEN_EXPIRED: "PASSWORD_RESET_TOKEN_EXPIRED",
  PASSWORD_RESET_NOT_ALLOWED: "PASSWORD_RESET_NOT_ALLOWED",
} as const;

export type AuthErrorCode = keyof typeof AUTH_ERROR_CODES;
