export const COMMON_ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  NETWORK_ERROR: "NETWORK_ERROR",
  SCHEMA_MISMATCH: "SCHEMA_MISMATCH",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INVALID_JSON: "INVALID_JSON",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
} as const;

export type CommonErrorCode = keyof typeof COMMON_ERROR_CODES;
