export const REPO_ERROR_CODES = {
  REPOSITORY_UNREACHABLE: "REPOSITORY_UNREACHABLE",
  INVALID_URL_FORMAT: "INVALID_URL_FORMAT",
  REPO_NOT_FOUND: "REPO_NOT_FOUND",
};

export type RepoErrorCode = keyof typeof REPO_ERROR_CODES;
