export const REPO_ERROR_CODES = {
  REPOSITORY_UNREACHABLE: "REPOSITORY_UNREACHABLE",
  REPOSITORY_ALREADY_EXISTS: "REPOSITORY_ALREADY_EXISTS",
} as const;

export type RepoErrorCode = keyof typeof REPO_ERROR_CODES;
